/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EduSys.Poly.UI;

import EduSys.utils.MsgBox;
import EduSysDAO.NhanVienDAO;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import EduSys.utils.Auth;
import EduSys.utils.MsgBox;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;


/**
 *
 * @author 84934
 */
public class DoiMatKhauJDialog extends javax.swing.JFrame {
   NhanVienDAO dao = new NhanVienDAO();
    private String otpStr; // Khai báo biến toàn cục
    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhauJDialog() {
        initComponents();
                setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPasssMoi = new javax.swing.JPasswordField();
        txtPassMoi2 = new javax.swing.JPasswordField();
        txtPasss = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        btnLayMa = new javax.swing.JButton();
        txtXNOTP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("EduSys/Poly/UI/Bundle"); // NOI18N
        jLabel3.setText(bundle.getString("DoiMatKhauJDialog.jLabel3.text")); // NOI18N

        btnLogin.setBackground(new java.awt.Color(51, 51, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText(bundle.getString("DoiMatKhauJDialog.btnLogin.text")); // NOI18N
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(bundle.getString("DoiMatKhauJDialog.jButton2.text")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(bundle.getString("DoiMatKhauJDialog.jLabel4.text")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(bundle.getString("DoiMatKhauJDialog.jLabel12.text")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(bundle.getString("DoiMatKhauJDialog.jLabel13.text")); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(bundle.getString("DoiMatKhauJDialog.jLabel14.text")); // NOI18N

        txtPasssMoi.setBackground(new java.awt.Color(0, 0, 0));
        txtPasssMoi.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        txtPasssMoi.setForeground(new java.awt.Color(255, 255, 255));
        txtPasssMoi.setText(bundle.getString("DoiMatKhauJDialog.txtPasssMoi.text")); // NOI18N

        txtPassMoi2.setBackground(new java.awt.Color(0, 0, 0));
        txtPassMoi2.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        txtPassMoi2.setForeground(new java.awt.Color(255, 255, 255));
        txtPassMoi2.setText(bundle.getString("DoiMatKhauJDialog.txtPassMoi2.text")); // NOI18N

        txtPasss.setBackground(new java.awt.Color(0, 0, 0));
        txtPasss.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        txtPasss.setForeground(new java.awt.Color(255, 255, 255));
        txtPasss.setText(bundle.getString("DoiMatKhauJDialog.txtPasss.text")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(bundle.getString("DoiMatKhauJDialog.jLabel15.text")); // NOI18N

        btnLayMa.setBackground(new java.awt.Color(153, 153, 153));
        btnLayMa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLayMa.setForeground(new java.awt.Color(255, 255, 255));
        btnLayMa.setText(bundle.getString("DoiMatKhauJDialog.btnLayMa.text")); // NOI18N
        btnLayMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayMaActionPerformed(evt);
            }
        });

        txtXNOTP.setBackground(new java.awt.Color(0, 0, 0));
        txtXNOTP.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        txtXNOTP.setForeground(new java.awt.Color(255, 255, 255));
        txtXNOTP.setText(bundle.getString("DoiMatKhauJDialog.txtXNOTP.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPasssMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txtPassMoi2)
                            .addComponent(txtPasss)
                            .addComponent(txtXNOTP))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin)
                        .addGap(90, 90, 90)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(btnLayMa)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasss, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtPasssMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtPassMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnLayMa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(txtXNOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(jButton2))
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 620, 530));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/111111111.jpg"))); // NOI18N
        jLabel2.setText(bundle.getString("DoiMatKhauJDialog.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

      String strMaNV = Auth.user.getMaNV();
        String strMatKhau = new String(txtPasss.getPassword());
        String strMatKhauMoi = new String(txtPasssMoi.getPassword());
        String strMatKhauMoi2 = new String(txtPassMoi2.getPassword());
        String strOTP = txtXNOTP.getText();

        if (Auth.user == null) {
            MsgBox.alert(this, "Không thể đổi mật khẩu. Vui lòng đăng nhập lại!");
        } else if (!strMaNV.equalsIgnoreCase(Auth.user.getMaNV())) {
            MsgBox.alert(this, "Sai tên đăng nhập!");
        } else if (!strMatKhau.equals(Auth.user.getMatKhau())) {
            MsgBox.alert(this, "Sai mật khẩu!");
        } else if (!strMatKhauMoi.equals(strMatKhauMoi2)) {
            MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
        } else if (!strOTP.equals(otpStr)) {
            MsgBox.alert(this, "OTP sai! Vui lòng nhập lại!");
        } else {
            int option = JOptionPane.showOptionDialog(this, "Bạn có chắc muốn đổi mật khẩu", "Xác nhận",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    new Object[]{"Yes", "No"}, "No");

            if (option == JOptionPane.YES_OPTION) {
                Auth.user.setMatKhau(strMatKhauMoi);
                dao.update(Auth.user);
                MsgBox.alert(this, "Đổi mật khẩu thành công!");
                Thread loadingThread = new Thread(new Runnable() {
                    public void run() {
                        try {
                            // Giả lập quá trình tải dữ liệu trong 2 giây
                            Thread.sleep(1000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }

                        // Tạo và hiển thị form đăng nhập sau khi quá trình tải dữ liệu hoàn thành
                        SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                EduSysJFrame p = new EduSysJFrame();
                                p.setVisible(true);
                            }
                        });

                        // Đóng form hiện tại
                        dispose();
                    }
                });

                loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu

            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int option = JOptionPane.showOptionDialog(this, "Bạn chắc muốn thoát chương trình", "Xác nhận",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            new Object[]{"Yes", "No"}, "No");

        if (option == JOptionPane.YES_OPTION) {
            Thread loadingThread = new Thread(new Runnable() {
                public void run() {
                    try {
                        // Giả lập quá trình tải dữ liệu trong 2 giây
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    // Tạo và hiển thị form đăng nhập sau khi quá trình tải dữ liệu hoàn thành
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            EduSysJFrame p = new EduSysJFrame();
                            p.setVisible(true);
                        }
                    });

                    // Đóng form hiện tại
                    dispose();
                }
            });

            loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLayMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayMaActionPerformed
        // Cấu hình thông tin tài khoản email
        Properties p = new Properties();
        p.put("mail.smtp.auth", "true");
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.put("mail.smtp.port", "587");
        p.put("mail.smtp.socketFactory.port", "587");
        p.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        p.put("mail.smtp.ssl.protocols", "TLSv1.2");

        String accountName = "dinhlhpc05738@fpt.edu.vn";
        String accountPasWord = "hfknngueqzmwtljg";

        // Tạo một phiên làm việc mới để gửi email
        Session session = Session.getDefaultInstance(p, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(accountName, accountPasWord);
            }
        });

        try {
            // Tạo đối tượng MimeMessage để gửi email
            MimeMessage message = new MimeMessage(session);

            // Thiết lập thông tin người gửi và người nhận
            message.setFrom(new InternetAddress(accountName));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress("dlehoang415@gmail.com"));

            // Tạo mã OTP ngẫu nhiên
            Random random = new Random();
            int otp = random.nextInt(900000) + 100000; // Tạo một số ngẫu nhiên có 6 chữ số
            otpStr = Integer.toString(otp); // Gán giá trị của số ngẫu nhiên cho biến otpStr

            // Thiết lập tiêu đề và nội dung email
            message.setSubject("Mã OTP của bạn");
            message.setText("Đây là mã OTP của bạn: " + otpStr);

            // Gửi email
            Transport.send(message);
            System.out.println("OTP đã được gửi!");
        } catch (MessagingException mex) {
            mex.printStackTrace();
        }

    }//GEN-LAST:event_btnLayMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhauJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLayMa;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassMoi2;
    private javax.swing.JPasswordField txtPasss;
    private javax.swing.JPasswordField txtPasssMoi;
    private javax.swing.JTextField txtXNOTP;
    // End of variables declaration//GEN-END:variables
}
