/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EduSys.Poly.UI;

import EduSys.utils.Auth;
import EduSys.utils.MsgBox;
import EduSys.utils.XImage;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author 84934
 */
public class EduSysJFrame extends javax.swing.JFrame {

    /**
     * Creates new form manhinhchinhdđ
     */
    public EduSysJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        dongHo();
        setIconImage(XImage.getAppicon());

    }

    public void dongHo() {
        Thread t = new Thread(new Runnable() {
            public void run() {
                try {
                    while (true) {
                        Date ngaygio = new Date();
                        SimpleDateFormat kieu = new SimpleDateFormat();
//                       kieu.applyPattern("dd/MM/yyyy");ngày tháng năm
                        kieu.applyPattern("hh:mm:ss:aa");
                        String dongHo = kieu.format(ngaygio);
                        lbldongHo.setText(dongHo);

                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        });
        t.start();

    }

    void openThongKe(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xem doanh thu");
            } else {

                Thread loadingThread = new Thread(new Runnable() {
                    public void run() {
                        try {
                            // Giả lập quá trình tải dữ liệu trong 2 giây
                            Thread.sleep(1000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }

                        // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                        SwingUtilities.invokeLater(new Runnable() {
                            private Frame manhinhchinhdđ;

                            public void run() {
                                new THONGKEJDIALOG(manhinhchinhdđ, true).setVisible(true);

                            }
                        });

                        // Đóng form hiện tại
                        dispose();
                    }
                });

                loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu

            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu7 = new javax.swing.JMenu();
        lbldongHo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoHoc = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuDangNhap = new javax.swing.JMenuItem();
        menuDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnKetThuc = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnChuyenDe = new javax.swing.JMenuItem();
        mnKhoahoc = new javax.swing.JMenuItem();
        mnNguoiHoc = new javax.swing.JMenuItem();
        mnHocVien = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnNhanVien = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnBangDiem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnLuongNguoiHoc = new javax.swing.JMenuItem();
        mnDiemChuyenDe = new javax.swing.JMenuItem();
        mnDoanhThu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("EduSys/Poly/UI/Bundle"); // NOI18N
        jMenu1.setText(bundle.getString("EduSysJFrame.jMenu1.text")); // NOI18N

        jMenuItem1.setText(bundle.getString("EduSysJFrame.jMenuItem1.text")); // NOI18N

        jMenuItem2.setText(bundle.getString("EduSysJFrame.jMenuItem2.text")); // NOI18N

        jMenu2.setText(bundle.getString("EduSysJFrame.jMenu2.text")); // NOI18N

        jMenu7.setText(bundle.getString("EduSysJFrame.jMenu7.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldongHo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbldongHo.setForeground(new java.awt.Color(255, 0, 51));
        lbldongHo.setText(bundle.getString("EduSysJFrame.lbldongHo.text")); // NOI18N
        lbldongHo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbldongHoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lbldongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, 90, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anh.jpg"))); // NOI18N
        jLabel2.setText(bundle.getString("EduSysJFrame.jLabel2.text")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 850, 470));

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit.png"))); // NOI18N
        btnDangXuat.setText(bundle.getString("EduSysJFrame.btnDangXuat.text")); // NOI18N
        btnDangXuat.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(102, 204, 255)));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Stop.png"))); // NOI18N
        jButton2.setText(bundle.getString("EduSysJFrame.jButton2.text")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), new java.awt.Color(153, 255, 153)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 100, 50));

        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/List.png"))); // NOI18N
        btnChuyenDe.setText(bundle.getString("EduSysJFrame.btnChuyenDe.text")); // NOI18N
        btnChuyenDe.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153)));
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        getContentPane().add(btnChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 100, 50));

        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login;;;;;;.png"))); // NOI18N
        btnNguoiHoc.setText(bundle.getString("EduSysJFrame.btnNguoiHoc.text")); // NOI18N
        btnNguoiHoc.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 153, 255), new java.awt.Color(204, 204, 255)));
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        getContentPane().add(btnNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 100, 50));

        btnKhoHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/copy.png"))); // NOI18N
        btnKhoHoc.setText(bundle.getString("EduSysJFrame.btnKhoHoc.text")); // NOI18N
        btnKhoHoc.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 255, 102), new java.awt.Color(153, 255, 0)));
        btnKhoHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoHocActionPerformed(evt);
            }
        });
        getContentPane().add(btnKhoHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 100, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Address book.png"))); // NOI18N
        jButton6.setText(bundle.getString("EduSysJFrame.jButton6.text")); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 255), new java.awt.Color(51, 255, 204)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 100, 50));

        btnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-male-user-23.png"))); // NOI18N
        btnHocVien.setText(bundle.getString("EduSysJFrame.btnHocVien.text")); // NOI18N
        btnHocVien.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), new java.awt.Color(255, 0, 255)));
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });
        getContentPane().add(btnHocVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/.....................png"))); // NOI18N
        jLabel1.setText(bundle.getString("EduSysJFrame.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -30, -1, -1));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -20, -1, -1));

        jMenu3.setText(bundle.getString("EduSysJFrame.jMenu3.text")); // NOI18N

        menuDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/.....................png"))); // NOI18N
        menuDangNhap.setText(bundle.getString("EduSysJFrame.menuDangNhap.text")); // NOI18N
        menuDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangNhapActionPerformed(evt);
            }
        });
        jMenu3.add(menuDangNhap);

        menuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Log out.png"))); // NOI18N
        menuDangXuat.setText(bundle.getString("EduSysJFrame.menuDangXuat.text")); // NOI18N
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        jMenu3.add(menuDangXuat);
        jMenu3.add(jSeparator1);

        mnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Refresh.png"))); // NOI18N
        mnDoiMatKhau.setText(bundle.getString("EduSysJFrame.mnDoiMatKhau.text")); // NOI18N
        mnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu3.add(mnDoiMatKhau);
        jMenu3.add(jSeparator2);

        mnKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Stop.png"))); // NOI18N
        mnKetThuc.setText(bundle.getString("EduSysJFrame.mnKetThuc.text")); // NOI18N
        mnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKetThucActionPerformed(evt);
            }
        });
        jMenu3.add(mnKetThuc);

        jMenuBar1.add(jMenu3);

        jMenu4.setText(bundle.getString("EduSysJFrame.jMenu4.text")); // NOI18N

        mnChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/List.png"))); // NOI18N
        mnChuyenDe.setText(bundle.getString("EduSysJFrame.mnChuyenDe.text")); // NOI18N
        mnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChuyenDeActionPerformed(evt);
            }
        });
        jMenu4.add(mnChuyenDe);

        mnKhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/copy.png"))); // NOI18N
        mnKhoahoc.setText(bundle.getString("EduSysJFrame.mnKhoahoc.text")); // NOI18N
        mnKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKhoahocActionPerformed(evt);
            }
        });
        jMenu4.add(mnKhoahoc);

        mnNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login;;;;;;.png"))); // NOI18N
        mnNguoiHoc.setText(bundle.getString("EduSysJFrame.mnNguoiHoc.text")); // NOI18N
        mnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNguoiHocActionPerformed(evt);
            }
        });
        jMenu4.add(mnNguoiHoc);

        mnHocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-male-user-23.png"))); // NOI18N
        mnHocVien.setText(bundle.getString("EduSysJFrame.mnHocVien.text")); // NOI18N
        mnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHocVienActionPerformed(evt);
            }
        });
        jMenu4.add(mnHocVien);
        jMenu4.add(jSeparator3);

        mnNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.....png"))); // NOI18N
        mnNhanVien.setText(bundle.getString("EduSysJFrame.mnNhanVien.text")); // NOI18N
        mnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNhanVienActionPerformed(evt);
            }
        });
        jMenu4.add(mnNhanVien);

        jMenuBar1.add(jMenu4);

        jMenu5.setText(bundle.getString("EduSysJFrame.jMenu5.text")); // NOI18N

        mnBangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Calendar.png"))); // NOI18N
        mnBangDiem.setText(bundle.getString("EduSysJFrame.mnBangDiem.text")); // NOI18N
        mnBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBangDiemActionPerformed(evt);
            }
        });
        jMenu5.add(mnBangDiem);
        jMenu5.add(jSeparator4);

        mnLuongNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnLuongNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Bar chart.png"))); // NOI18N
        mnLuongNguoiHoc.setText(bundle.getString("EduSysJFrame.mnLuongNguoiHoc.text")); // NOI18N
        mnLuongNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLuongNguoiHocActionPerformed(evt);
            }
        });
        jMenu5.add(mnLuongNguoiHoc);

        mnDiemChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnDiemChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Best.png"))); // NOI18N
        mnDiemChuyenDe.setText(bundle.getString("EduSysJFrame.mnDiemChuyenDe.text")); // NOI18N
        mnDiemChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiemChuyenDeActionPerformed(evt);
            }
        });
        jMenu5.add(mnDiemChuyenDe);

        mnDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        mnDoanhThu.setText(bundle.getString("EduSysJFrame.mnDoanhThu.text")); // NOI18N
        mnDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDoanhThuActionPerformed(evt);
            }
        });
        jMenu5.add(mnDoanhThu);

        jMenuBar1.add(jMenu5);

        jMenu6.setText(bundle.getString("EduSysJFrame.jMenu6.text")); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Address book.png"))); // NOI18N
        jMenuItem3.setText(bundle.getString("EduSysJFrame.jMenuItem3.text")); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);
        jMenu6.add(jSeparator5);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Open letter.png"))); // NOI18N
        jMenuItem4.setText(bundle.getString("EduSysJFrame.jMenuItem4.text")); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbldongHoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbldongHoAncestorAdded
        // TODO add your handling code here:
        dongHo();
    }//GEN-LAST:event_lbldongHoAncestorAdded

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int option = JOptionPane.showOptionDialog(this, "Bạn chắc muốn thoát chương trình", "Xác nhận",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                new Object[]{"Yes", "No"}, "No");

        if (option == JOptionPane.YES_OPTION) {

            // Đóng form hiện tại
            dispose();

        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
         if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new ChuyenDeJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
        
        
       
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
     if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new NguoiHocJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
        

    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnKhoHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoHocActionPerformed
        if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new KhoaHocJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_btnKhoHocActionPerformed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
          if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new HocVienJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form đăng nhập sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        GioiThieuJDialog p = new GioiThieuJDialog();
                        p.setVisible(true);
                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        
                if (Auth.isLogin()) {
         
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed
        int option = JOptionPane.showOptionDialog(this, "Bạn chắc muốn thoát chương trình", "Xác nhận",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                new Object[]{"Yes", "No"}, "No");

        if (option == JOptionPane.YES_OPTION) {
            Thread loadingThread = new Thread(new Runnable() {
                public void run() {
                    try {
                        // Giả lập quá trình tải dữ liệu trong 2 giây
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    // Tạo và hiển thị form đăng nhập sau khi quá trình tải dữ liệu hoàn thành
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            DangNhapJDialog p = new DangNhapJDialog();
                            p.setVisible(true);
                        }
                    });

                    // Đóng form hiện tại
                    dispose();
                }
            });

            loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu   
        }
    }//GEN-LAST:event_menuDangXuatActionPerformed

    private void mnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNhanVienActionPerformed
             if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new NhanVienJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mnNhanVienActionPerformed

    private void mnDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoanhThuActionPerformed
        openThongKe(3);       // TODO add your handling code here:
    }//GEN-LAST:event_mnDoanhThuActionPerformed

    private void mnLuongNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLuongNguoiHocActionPerformed
        openThongKe(1);

    }//GEN-LAST:event_mnLuongNguoiHocActionPerformed

    private void mnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoiMatKhauActionPerformed
        Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form đăng nhập sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        DoiMatKhauJDialog p = new DoiMatKhauJDialog();
                        p.setVisible(true);
                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu     


    }//GEN-LAST:event_mnDoiMatKhauActionPerformed

    private void menuDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangNhapActionPerformed
        Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form đăng nhập sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        DangNhapJDialog p = new DangNhapJDialog();
                        p.setVisible(true);
                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
    }//GEN-LAST:event_menuDangNhapActionPerformed

    private void mnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKetThucActionPerformed
        int option = JOptionPane.showOptionDialog(this, "Bạn chắc muốn thoát chương trình", "Xác nhận",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                new Object[]{"Yes", "No"}, "No");

        if (option == JOptionPane.YES_OPTION) {

            // Đóng form hiện tại
            dispose();

        }
    }//GEN-LAST:event_mnKetThucActionPerformed

    private void mnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChuyenDeActionPerformed
        if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new ChuyenDeJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
        
        
    }//GEN-LAST:event_mnChuyenDeActionPerformed

    private void mnKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKhoahocActionPerformed
     if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new KhoaHocJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
        
        
    }//GEN-LAST:event_mnKhoahocActionPerformed

    private void mnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNguoiHocActionPerformed
          if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new NguoiHocJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mnNguoiHocActionPerformed

    private void mnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHocVienActionPerformed
                if (Auth.isLogin()) {
             Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form NguoiHocJDialog sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    private Frame manhinhchinhdđ;

                    public void run() {
                        new HocVienJDialog(manhinhchinhdđ, true).setVisible(true);

                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mnHocVienActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBangDiemActionPerformed
        openThongKe(0);
    }//GEN-LAST:event_mnBangDiemActionPerformed

    private void mnDiemChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiemChuyenDeActionPerformed
        openThongKe(2);

    }//GEN-LAST:event_mnDiemChuyenDeActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Thread loadingThread = new Thread(new Runnable() {
            public void run() {
                try {
                    // Giả lập quá trình tải dữ liệu trong 2 giây
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // Tạo và hiển thị form đăng nhập sau khi quá trình tải dữ liệu hoàn thành
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        GioiThieuJDialog p = new GioiThieuJDialog();
                        p.setVisible(true);
                    }
                });

                // Đóng form hiện tại
                dispose();
            }
        });

        loadingThread.start(); // Bắt đầu tiến trình tải dữ liệu
        
                if (Auth.isLogin()) {
         
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EduSysJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnKhoHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lbldongHo;
    private javax.swing.JMenuItem menuDangNhap;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenuItem mnBangDiem;
    private javax.swing.JMenuItem mnChuyenDe;
    private javax.swing.JMenuItem mnDiemChuyenDe;
    private javax.swing.JMenuItem mnDoanhThu;
    private javax.swing.JMenuItem mnDoiMatKhau;
    private javax.swing.JMenuItem mnHocVien;
    private javax.swing.JMenuItem mnKetThuc;
    private javax.swing.JMenuItem mnKhoahoc;
    private javax.swing.JMenuItem mnLuongNguoiHoc;
    private javax.swing.JMenuItem mnNguoiHoc;
    private javax.swing.JMenuItem mnNhanVien;
    // End of variables declaration//GEN-END:variables

}
